# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-15 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='respCorrecta',
            field=models.IntegerField(default=1),
        ),
    ]
